const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
  },
  USER: {
    CREATE: "CREATE_USER",
    GET: "GET_USERS",
    DISCONNECTED: "USER_DISCONNECTED",
  },

  MESSAGE: {
    SEND: "SEND_MESSAGE",
    GET: "GET_MESSAGE",
  },
};
export default EVENTS;
